[tool.poetry]
name = "openbb"
version = "4.0.0"
description = ""
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb" }, { include = "builtin_extensions" }]

[tool.poetry.dependencies]
python = "^3.9"
openbb_sdk_core = "^0.2.0"
openbb_provider = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
